### PR TITLE
Fix html title tag for the install article

### PR DESCRIPTION
**Pull request by ultimape**
There appeared to be a copy/paste error inside of the <title></title> tag. I fixed it to match the index.html format.

### CODE REVIEW

**Comment by ultimape** [comment]
Just noticed this is a generated file. I think I found out what I actually have to fix. Seeing if I can add to this commit.

**Comment by ultimape** [comment]
That should do it. Pkgdown seems to be grabbing the "1. " part of the title and applying conversions rules html blindly. It seemed to have been converted to an ordered list with one item.  But the title tag doesn't support that. As far as I am aware, only it only supports text.

Removing the "1. " should prevent the way it does markdown conversion from triggering. 
I don't have the workflow set up to actually test this though.

**Comment by sjmgarnier** [comment]
@ultimape This is a problem I have always had with pgkdown. Removing `1.` will fix this problem, but will create another one unfortunately. Pkgdown orders the articles in the menu bar by alphabetical order. This means that I cannot force the installation article to always be first in the hierarchy. This is not a problem now since there is only 1 article, but it will become one later once I have created more help articles.

**Comment by ultimape** [comment]
Oh darn. That is very strange!

If I have some time I'll see if I can recreate it and maybe find out if
there is a work around.

Do you have any other repos that ran into the alphabetical sorting problem
I could use as an example?

I've been meaning to play with this stuff anyway.

Feel free to reject this pull request.

**Comment by sjmgarnier** [comment]
@ultimape I suggest you remove this PR for now and open an issue instead so that we can keep a record of this problem. I have the same problem every time I use pkgdown with one of my packages (e.g. Rvision and ROpenCVLite). I think it might be worth opening an issue on the pkgdown repo at some point.

**Comment by sjmgarnier** [comment]
@ultimape I have resolved the problem by using a dash instead of a dot in the title of each article. It doesn't really fix the bug, it just makes it disappears :-)

**Pull request closed without merging**
